### ISSUE TITLE
Compiler errror for AddLargeStrings

### ISSUE THREAD

**Issue by tbeu** [modelica-compliance/compliance#14]
ModelicaCompliance.Operators.Arithmetic.AddLargeStrings leads to a [fatal compiler error C1091](https://msdn.microsoft.com/en-US/library/f27ch0t1%28v=vs.80%29.aspx) for string constants exceeding the maximum length of 65k Bytes. Is this really the desired scenario to be tested?

GCC (also for MinGW) does not have this problem.

**Comment by perost** [comment]
This test was added by @sjoelund, so he will have to explain the reason for this test. He's in China at the moment though, and will be back next week.

**Comment by sjoelund** [comment]
The test was initially added to test that the Modelica compiler frontend does not crash on large strings (@dietmarw had problems with Modelica tools doing this at the time ModelicaCompliance was being developed). There are no limitations on string length in Modelica, but some C-compilers have this problem, so the translating tool needs to take care to split strings in such a way that the C-compiler can handle the code.

**Comment by tbeu** [comment]
OK. Thanks.
